### ISSUE TITLE
TextRank

### ISSUE THREAD

**Issue by lambdaofgod** [mahnazkoupaee/WikiHow-Dataset#14]
The article mentions using TextRank. What implementation did you use?

Specifically, most TextRank implementations need to specify either number of words or ratio of words to extract from text - ROUGE is very sensitive to that, as increasing this can decrease it, or at least keep it constant (there is no penalty for increasing this parameter).

**Comment by mahnazkoupaee** [comment]
We used the following implementation of TextRank:
 
https://github.com/summanlp/textrank

You can either define the approximate number (it generates complete sentences without truncation) of words for your summary or the ratio of words to be extracted from the text. 
Since the structure of the article sentences and the summary sentences are different (sentences in the former are longer), We used a larger number of words (100) to extract sentences from the article so that we could have summaries covering a larger portion of the text. For other systems, we used a summary length of 35 at decoding time. 
Using 35 as the length for TextRank results in lower ROUGE scores as the summary is very limited in coverage.

**Comment by lambdaofgod** [comment]
I just ran textrank on your proposed test dataset (I used exactly the same preprocessing as your script) and got

rouge-1    0.344806
rouge-2    0.090868
rouge-l    0.325432

Did you use whole texts as input or did you truncate it as in abstractive setting?

**Comment by mahnazkoupaee** [comment]
Did you use python 2 or python 3 to run pyrouge?

**Comment by lambdaofgod** [comment]
I used different implementation, I'll check pyrouge. BTW what pyrouge version did you use? There are at least two I know of, one by andersjo and other by bheinzerling

**Comment by lambdaofgod** [comment]
Also, when ROUGE outputs 

1 ROUGE-1 Average_R: ...
1 ROUGE-1 Average_P: ...
1 ROUGE-1 Average_F: ...

Which one did you report?

**Comment by mahnazkoupaee** [comment]
You can have a look at https://github.com/abisee/pointer-generator (Evaluate with ROUGE) section to get familiar with how pyrouge is used. 

The scores reported in the paper are F-1 scores.

**Comment by mahnazkoupaee** [comment]
You can have a look at https://github.com/abisee/pointer-generator (Evaluate with ROUGE) section to get familiar with how pyrouge is used. 

The scores reported in the paper are F-1 scores.

**Comment by mahnazkoupaee** [comment]
You can have a look at https://github.com/abisee/pointer-generator (Evaluate with ROUGE section) to get familiar with how pyrouge is used. 

The scores reported in the paper are F-1 scores.
